### ISSUE TITLE
The news list renders correctly in preview, uikit and our prototype but not on the published page.

### ISSUE THREAD

**Issue by nicholasgkdto** [AusDTO/gov-au-beta#194]
published page
https://gov-au-beta-blue.apps.platform.digital.gov.au/minister-for-finance/news-57efb547-8012-4b1b-a35e-78ad06111778

UIkit
http://gov-au-ui-kit-staging.apps.staging.digital.gov.au/section-list-styles.html

prototype
http://govau-agency.apps.staging.digital.gov.au/announcements/2015-12-11-a-warm-reception-for-viewers-in-the-hunter.html

**Comment by ltankey** [comment]
Thanks @nicholasgkdto 

It looks like the primary reason behind this is the usage of HTML as input, as opposed to some semantic template we could create to reflect the desired layout.

We have a current task to display news for a given section, which should largely address this need. Given that the news page will likely be generated and won't require user input, I might close this and see if we can't fix it as part of SITES-403 - a user can view news for a section.
