### ISSUE TITLE
When I change the name of a minister page the title did not change

### ISSUE THREAD

**Issue by nicholasgkdto** [AusDTO/gov-au-beta#213]
I changed the name from "Minister for Health" to "Minister for Health and Aged Care" the title did not update.

https://gov-au-beta.apps.platform.digital.gov.au/minister-for-health-and-aged-care

**Comment by tessereth** [comment]
So we currently have both a section which determines the text in the hero banner and a section home node which is what you edited and which determines the slug and the breadcrumb text. These should both use the same value. I've filed it as a bug in our backlog.

**Comment by catherineedwards** [comment]
This is being addressed in `SITES-419`
