### ISSUE TITLE
Side nav for Depts and Ministers issue

### ISSUE THREAD

**Issue by michaelhugill** [AusDTO/gov-au-beta#229]
The top item in the right hand nav on the prototype takes you to the landing page for that section, but that doesn’t happen in the platform – is that deliberate?

Maybe compare the side nav here: 
With the side nav here: 

Side nav is probably still under contention, but I noticed this on department and minister pages in the platform - neither of them have a top side nav item that links to the landing page. Will leave with you guys.

**Comment by ltankey** [comment]
I believe there was specifics about this coming from the ui-kit folk. We need to touch base with them to get their take on the interaction, as I believe they had opinions on this.

**Comment by streetdaddy** [comment]
'Bug' logged in Design Guide DESIGN-266

**Comment by ltankey** [comment]
Delivered in v0.9.0
