### ISSUE TITLE
Hero banner implementation

### ISSUE THREAD

**Issue by simonschwartz** [AusDTO/gov-au-beta#233]
Currently the hero banner appears on all pages which is incorrect

The correct pattern is to show the **large** hero banner on the section landing page eg Department landing page, Minister landing page. There should be no link in the hero banner. The text should be the section heading.

On all other pages a **small** version of the hero banner with the section heading.

The `<h1>` should still be rendered on landing pages in the same way as all other section pages however it should be visually hidden using `.visually-hidden`.

**Images of correct implementation to come**

**Comment by maxious** [comment]
Confirmed this happening on prototype. 
Does the padding without the hero before the h1 need to be bigger like it is on the prototype?

**Comment by simonschwartz** [comment]
@maxious yep - this is addressed by #227

**Comment by tessereth** [comment]
This is in the backlog as SITES-436

**Comment by ltankey** [comment]
Delivered in v0.9.0
