### ISSUE TITLE
Accordions

### ISSUE THREAD

**Issue by simonschwartz** [AusDTO/gov-au-beta#234]
Content on the [contact us](http://govau-agency.apps.staging.digital.gov.au/comms-arts-agency/contact-us-comms.html) page is organised in accordions.

Markup can be found at http://gov-au-ui-kit.apps.staging.digital.gov.au/section-accordions.html

Would be great to be able to publish content using accordions in the platform

**Comment by catherineedwards** [comment]
See `SITES-437` for progress on this issue.
