### ISSUE TITLE
Short summary not displaying

### ISSUE THREAD

**Issue by michaelhugill** [AusDTO/gov-au-beta#252]
I just moved some text out of body text and into the short summary field of this page: https://gov-au-beta.apps.platform.digital.gov.au/minister-for-finance/about-the-minister
It’s there on the CMS side, but it’s not showing up on the published page. Any ideas?

**Comment by tessereth** [comment]
Fixed in #247. Will be included in the next release.

**Comment by nicholasgkdto** [comment]
@tessereth Will this fix the "summary" not showing up in news items?  short summary works in news.

**Comment by ltankey** [comment]
@nicholasgkdto currently you can create a long summary
![image](https://cloud.githubusercontent.com/assets/5369670/17161731/215840b2-53f3-11e6-882a-727446dbb844.png)
for a news article.

Was there a particular instance this field was not available?

**Comment by nicholasgkdto** [comment]
@ltankey  This page
`platfrom/department-of-communications-and-the-arts/news/2016-04-29-nbn-satellite-service-opens-for-business`
should show a summary, i put in the words "This is a summary" in and it does not appear. short summary appears.

**Comment by tessereth** [comment]
Yes, the PR I referenced will make the summary (soon to be called long summary) appear on all pages (news or otherwise).
