### ISSUE TITLE
Short summary and sectionhomes aka landing pages

### ISSUE THREAD

**Issue by michaelhugill** [AusDTO/gov-au-beta#258]
I’ve noticed the sectionhomes aka landing pages in the CMS don’t have the ‘short summary’ field which means that authors would be forced to place their short summaries inside the body text area (and potentially miss the styling associated with the short summary field).

At this stage I can't see an argument for a sectionhome aka landing page having a summary (aka long summary) field, but so far all minister and department landing pages definitely need short summaries visible to users.

**Comment by ltankey** [comment]
Hi @michaelhugill, no problem, this will be delivered as part of the next release.

Worthy of note (but not directly related to this issue) - section_homes do not have a h1 as it stands. I've placed the short-summary at the top of the page, but we will need to resolve this as a separate issue.
