### ISSUE TITLE
Summary field labels

### ISSUE THREAD

**Issue by michaelhugill** [AusDTO/gov-au-beta#259]
Hi @ltankey, looks like something we discussed on Slack didn't quite make it to Github and the platform.

I've noticed that the field labels in the CMS are 'short summary' and 'summary', but we were hoping for 'short summary' and 'long summary'. 

The back story here is that we don't want any confusion for authors so we thought it important that both fields have distinct names, ie short and long. 

Would it be easy to make that change?

**Comment by ltankey** [comment]
Hi @michaelhugill thanks for raising this - it will be addressed in the next release.

**Comment by michaelhugill** [comment]
Not critical (but worth recording): @ltankey I've noticed that the 'long summary' field is no longer present in CMS pages. Is this something that will come back later?

'Short summary' is there and working fine.

**Comment by ltankey** [comment]
What page is this happening for @michaelhugill? I've just checked where it was added and it should still be working. Does the page have content for long summary?

**Comment by ltankey** [comment]
Long summary has dropped off due to a bug.

**Comment by ltankey** [comment]
Delivered in v0.9.0
