### ISSUE TITLE
Dates in news listing on minsters and department landing pages should follow style guide

### ISSUE THREAD

**Issue by nicholasgkdto** [AusDTO/gov-au-beta#264]
The date currently displays as 2016-04-29 and not 29 April 2016

platform/department-of-communications-and-the-arts#news

**Comment by ltankey** [comment]
Thanks @nicholasgkdto - please leave the domain off in future.

**Comment by tessereth** [comment]
In backlog as SITES-465

**Comment by ltankey** [comment]
Fixed in v0.7.0
