### ISSUE TITLE
Minister, department and topic news listing pages should show side menu and breadcrumbs

### ISSUE THREAD

**Issue by nicholasgkdto** [AusDTO/gov-au-beta#266]
The news listing page on Minister, department and topic,
eg `platform/department-of-communications-and-the-arts/news`
should have the same menu and breadcrumb style as the our role
eg `platform/department-of-communications-and-the-arts/our-role`

**Comment by streetdaddy** [comment]
https://govausites.atlassian.net/browse/SITES-474 seems to cover some of this.

**Comment by streetdaddy** [comment]
as does https://govausites.atlassian.net/browse/DESIGN-270

**Comment by Alex-DTO** [comment]
Looks like they're displaying Global News pages instead of pages filtered by the topic / dept etc

**Comment by tessereth** [comment]
@nicholasgkdto Should the menu also appear on an individual news article page?

**Comment by Alex-DTO** [comment]
@tessereth - nope. News articles, once being viewed, are free of nav structure.

i.e. http://govau-agency.apps.staging.digital.gov.au/announcements/2016-05-06-draft-report-review-acma.html

**Comment by tessereth** [comment]
Cool. Just checking. Thanks. Also for github linking purposes, this is the PR: #317.

**Comment by ltankey** [comment]
Delivered in v0.9.0
