### ISSUE TITLE
Can not update metadata of news item

### ISSUE THREAD

**Issue by nicholasgkdto** [AusDTO/gov-au-beta#271]
When i try to update the metadata of a news item i get the following error.

![image](https://cloud.githubusercontent.com/assets/19787722/17163680/131a6a4a-5405-11e6-92a5-8db7fbe5e1eb.png)

I click on edit metadata on this page
`platform/television-tv-reception/news/2016-07-22-a-warm-reception-for-viewers-in-the-hunter`

then this page opens
`platform/editorial/news/98/edit`

and when i click on the submit button, this page has the error above.
`platform/editorial/news/98`

**Comment by tessereth** [comment]
In backlog as SITES-467

**Comment by ltankey** [comment]
Fixed in v0.7.0
