### ISSUE TITLE
News item alignment on landing pages

### ISSUE THREAD

**Issue by michaelhugill** [AusDTO/gov-au-beta#275]
Hi, this may be a UI Kit issue – I'm not sure – but on any department or minister landing page, if the author/s have tagged only 2 news stories to appear there, those news stories are not left aligning. 

See attached or: https://gov-au-beta.apps.platform.digital.gov.au/department-of-communications-and-the-arts

We can fix this by adding a third news item but there might be cases in the future where there are only two stories and we'll have the same display issue.

![screen shot 2016-07-27 at 4 08 42 pm](https://cloud.githubusercontent.com/assets/17994414/17165567/9cf48eee-5414-11e6-8709-5252f81db28b.png)

**Comment by ltankey** [comment]
Hi @michaelhugill 

This is indeed an issue with the ui-kit. If you can raise it there we will be able to implement any resultant markup.

https://github.com/AusDTO/gov-au-ui-kit/issues

**Comment by michaelhugill** [comment]
Note: added to UI-Kit issues.
