### ISSUE TITLE
Check if correct markup is there for top item of side nav in sections

### ISSUE THREAD

**Issue by michaelhugill** [AusDTO/gov-au-beta#279]
@ltankey Just placing that Slack conversation you got tagged into here. Example pages include:
/department-of-communications-and-the-arts
/minister-for-finance

michael.hugill [11:13 AM] 
a couple of us have noticed that the top item in the right hand nav of platform pages is no longer the section name (linked to the section landing page). Do you know if that’s a bug or a UI-kit thing? Thanks.

treb [11:17 AM]  
We have a PR waiting for styles for that, but if the HTML is missing maybe contact Platforms and confirm that it's returning the correct markup
https://github.com/AusDTO/gov-au-ui-kit/pull/207

**Comment by ltankey** [comment]
Thanks @michaelhugill 

We'll liaise with the ui-kit team to ensure the correct markup is implemented.

**Comment by ltankey** [comment]
Duplicated of #229
