### ISSUE TITLE
Definition/description markdown parser support

### ISSUE THREAD

**Issue by klepas** [AusDTO/gov-au-beta#282]
After some huddles with Michael Hugill we discovered that the content team has been battling with the markdown syntax to visually get the content organised.

One page & section where this still occurs is: https://gov-au-beta.apps.platform.digital.gov.au/department-of-communications-and-the-arts/our-role#portfolio-agencies-we-work-with

Not only does the content team want the bullets removed, but semantically, these would be far more accurately marked-up in def/desc. lists.

Solution: use a markdown parser with definition list support. I’m particularly fond of Kramdown’s syntax:

```
Definition/desc. term
: definition

foo
: bar
: baz
: multiple dds woo!
```

**Comment by ltankey** [comment]
This is interesting, and I think we have a foundational ticket to begin addressing this on SITES-428 (As an author I can enter definition lists as markdown).

The challenge is that our rendered (redcarpet) doesn't support it, which means we'd have to move back to Kramdown. This in itself isn't a problem, but will require forking and change showdown.js to render the preview as per kramdown's spec (there's a difference in the spacing kramdown expects for headings).

This will also require changes to showdown to support previewing definition lists, as currently it does not support that. The MVP to get definition lists over the line would not require this, but it would be nice if part of the challenge is recognising when the syntax is right.

**Comment by klepas** [comment]
Damn, that sucks.

@ltankey could you advise on an interim solution? I’m getting the vibe that we might have to either insert HTML of def/desc lists, or we ignore this entirely for now. Do you have a preference?

**Comment by ltankey** [comment]
@klepas we could technically switch back to Kramdown to support definition lists (pending the necessary adjustment to showdown re: headings) and leave off the job of extending showdown to support them. This would mean they'd render server-side but wouldn't be previewed.

**Comment by klepas** [comment]
> An even more interim solution may well be taking on content-debt via manual HTML tags.

@coderdan had a chat with us about this, and we came up with this:

- we manually chuck some HTML into the content as required, probably pairing with content peeps
- we deal with the tech debt of hardcoding post-demo

@ltankey should this issue be closed now — anything worth lifting out into a backlog elsewhere?

**Comment by tessereth** [comment]
This is in our backlog as SITES-428 which has a reference to this issue so the conversation is recorded. Closing the issue for now.
