### ISSUE TITLE
When you click on department news article you should go to the global news section with the news header

### ISSUE THREAD

**Issue by streetdaddy** [AusDTO/gov-au-beta#284]
## What I did

Followed a Department News article link in the production platform, from page:

https://gov-au-beta.apps.platform.digital.gov.au/department-of-communications-and-the-arts (bottom of the page) ➡️ 
https://gov-au-beta.apps.platform.digital.gov.au/department-of-communications-and-the-arts/news/2016-05-06-aged-under-15-what-does-it-mean-for-classifications

## What I expected to see

News article displayed with the Global header, as per the Prototype:
http://govau-agency.apps.staging.digital.gov.au/comms-arts-agency/index.html ➡️ 
http://govau-agency.apps.staging.digital.gov.au/announcements/2015-12-11-a-warm-reception-for-viewers-in-the-hunter.html

## What I saw

News article displayed with Department (section) header

**Comment by ltankey** [comment]
Thanks @streetdaddy this is a duplicate of an issue raised in #265.

**Comment by streetdaddy** [comment]
Confirmed this is fixed in Production Platform since v0.7.0

See https://gov-au-beta.apps.platform.digital.gov.au/department-of-communications-and-the-arts/news/2016-07-27-support-for-festival-of-india-in-australia-2016
