### ISSUE TITLE
Inline links should have scroll animation

### ISSUE THREAD

**Issue by sarkirkby** [AusDTO/gov-au-beta#287]
**Steps to replicate:**
1. Go to a page with inline links (TOC), https://gov-au-beta.apps.platform.digital.gov.au/television-tv-reception/troubleshooting-tv-reception
2. Click on any anchor link
3. Page jumps to correct anchor

**Error:**
- When you click on the link it jumps straight to correct anchor without a smooth scroll animation

**Expected:**
- To see a smooth scroll animation, as per style in prototype http://govau-agency.apps.staging.digital.gov.au/tv-reception/setting-up-digital-tv.html. I believe this style is available in the UI framework.

**Comment by ltankey** [comment]
@sarkirkby I can't replicate this (it scrolls smoothly on mine) - what device/browser are you using?

**Comment by ltankey** [comment]
Reproduced - if you visit the page directly, smooth-scroll works. If you navigate there from the preceding page, it does not. This is likely due to turbolinks conflicting with how smooth-scroll is implemented.

**Comment by ltankey** [comment]
I suspect this block is the culprit from javascript.js of the ui-kit

```
	// We look for all the internal links in the documents and attach the smoothscroll function
	document.addEventListener("DOMContentLoaded", function () {
	    var internal = document.querySelectorAll('a[href^="#"]:not([href="#"])'), a;
	    for(var i=internal.length; a=internal[--i];){
	        a.addEventListener("click", linkHandler, false);
	    }
	});
```

http://stackoverflow.com/questions/27968469/smooth-scrolling-not-working-in-rails-unless-page-is-refreshed

**Comment by ltankey** [comment]
@sarkirkby I've raised this with the ui-kit team at https://github.com/AusDTO/gov-au-ui-kit/issues/223
