### ISSUE TITLE
Turn off blue tab focus outline in Dept section pages

### ISSUE THREAD

**Issue by sarkirkby** [AusDTO/gov-au-beta#296]
Steps to replicate:
- Go to https://gov-au-beta.apps.platform.digital.gov.au/department-of-communications-and-the-arts
- Click in the body area

Error:
- See blue tab focus around content area

Expected:
- Only see tab focus when tabbing into that area. It should not display when clicking in that area.

**Comment by streetdaddy** [comment]
@sarkirkby Which browser?

**Comment by sarkirkby** [comment]
Chrome

**Comment by sarkirkby** [comment]
Version 51.0.2704.103

**Comment by streetdaddy** [comment]
Triaged as SITES-494

**Comment by streetdaddy** [comment]
@sarkirkby you can track this via DESIGN-278
