### ISSUE TITLE
Sidebar navigation items >=3 levels are not using Design Guide styles

### ISSUE THREAD

**Issue by streetdaddy** [AusDTO/gov-au-beta#298]
/times-and-dates/australian-public-holidays

Reported by @gazhands (Gary)

Needs confiirmation CSS and HTML used is as per http://gov-au-ui-kit.apps.staging.digital.gov.au/section-navigation.html#guide-navigation-2-local-navigation to style navigation items >=3 levels deep

Not a problem for Demo, as there's no navigation this deep.

**Comment by streetdaddy** [comment]
triaged as SITES-495

**Comment by tessereth** [comment]
What are the correct design guide styles? What are we currently doing that's wrong? More detail required.

**Comment by gazhands** [comment]
Looks like it's been fixed. Uses active state (class="is-active") to show which page the user is on.

**Comment by gazhands** [comment]
Please close, thanks all

**Comment by streetdaddy** [comment]
@gazhands see https://gov-au-beta.apps.staging.digital.gov.au/businesssssssssssssssss/parent/child-c/3rd-level-navigation-item

Even though the the active page navigation item uses '''is-active''', it's still not styled as per the UI-kit ie. it should be highlighted with the blue background.

Can you please confirm?

**Comment by gazhands** [comment]
http://gov-au-ui-kit-staging.apps.staging.digital.gov.au/section-navigation.html#guide-navigation-2-local-navigation

**Comment by tessereth** [comment]
Fixed in v1.2.0
