### ISSUE TITLE
Group/"Popular" links breakpoints not reacting as expected

### ISSUE THREAD

**Issue by hannah-ustwo** [AusDTO/gov-au-beta#299]
Links should be appearing across 4 columns up until the mobile breakpoint where it changes to 2 columns.

Double checked and confirmed that it is working in the UI kit; appears to only be happening on the gov.au beta.

![e219af512cb3bd5c4cf386455d4ba5e3](https://cloud.githubusercontent.com/assets/19661064/17234119/21f29acc-5579-11e6-8347-a40e55690284.gif)

**Comment by ltankey** [comment]
Thanks @hannah-ustwo - the markup seems identical from the example provided on the ui-kit page.

Just to confirm, this is correct:

```
         <div class='links-group'>
            <h2>Popular links</h2>
            <ul class='popular-now'>
              <li>
                <a href="/times-and-dates/australian-public-holidays">Public Holiday dates</a>
              </li>
              <li>
                <a href="#">Lodge your tax return</a>
              </li>
              <li>
                <a href="#">Working in Australia</a>
              </li>
              <li>
                <a href="#">Visiting Australia</a>
              </li>
              <li>
                <a href="#">What can you bring to Australia</a>
              </li>
              <li>
                <a href="#">Citizenship</a>
              </li>
              <li>
                <a href="/times-and-dates/school-holidays-and-term-dates">School Holiday dates</a>
              </li>
              <li>
                <a href="#">Government Jobs</a>
              </li>
            </ul>
          </div>
```

**Comment by hannah-ustwo** [comment]
The markup looks right...any other clues to what might be making the breakpoints malfunction @klepas @petronbot ?

**Comment by ltankey** [comment]
@hannah-ustwo do you have any full-page examples that we might be able to look at? Is it possible some of the header changes have had flow-on effects? We are now using `prerelease-govau--header`.

**Comment by hannah-ustwo** [comment]
@ltankey Not sure if this is helpful, but we have an example page before we introduced the `prerelease-govau--header` [over here](http://gov-au-ui-kit.apps.staging.digital.gov.au/examples/group-links.html)

Looping in @treb, he's looking into it now.

**Comment by treb** [comment]
?????????

**Comment by TrebBrennan** [comment]
I'm guess you meant me. Sorry @treb please disregard

**Comment by hannah-ustwo** [comment]
Ooops...

**Comment by streetdaddy** [comment]
triaged as SITES-496

**Comment by treb** [comment]
?????????why are you sending me emails?

**Comment by hannah-ustwo** [comment]
Noob-servation: Having a look and a play...observing the CSS as the viewport drops below 1200px, and these media queries (screenshot below) disappear...

![image](https://cloud.githubusercontent.com/assets/19661064/17238899/f5236e02-55a2-11e6-8df3-4a6886e8e17e.png)

**Comment by ltankey** [comment]
Delivered in v1.0.0
