### ISSUE TITLE
Change Global News item titles from H2 to H3

### ISSUE THREAD

**Issue by streetdaddy** [AusDTO/gov-au-beta#307]
## Expected:

[Global News item titles in the Platform](https://gov-au-beta.apps.staging.digital.gov.au/news) should visually match the [Global News item titles in the Prototype](http://govau-agency.apps.staging.digital.gov.au/news.html)

![Prototype](https://www.evernote.com/l/ABZ-fxhRVrBEF7FR9pjlzamDockEP0PgUHgB/image.png)

## Actual:

It doesn't match the prototype:

![Platform](https://www.evernote.com/l/ABbsjbSoGxJEUL_uI3oZGG4RTZn2KTgy7YYB/image.png)

## Steps to reproduce:

* Visit the [Global News page in the Platform](https://gov-au-beta.apps.staging.digital.gov.au/news) 
* Compare to [Global News item titles in the Prototype](http://govau-agency.apps.staging.digital.gov.au/news.html)
* Behold

Nb. Changing from H2 to H3 is not semantically correct, but once the Sort Filter is added (future enhancement) it will be correct again, as this component has an H2 in the markup:

![Future enhancement Sort Filter with Global News listing](https://www.evernote.com/l/ABa1WoEKYhJGIoAVW18K-EwxQos7hFAiLzAB/image.png)

**Comment by streetdaddy** [comment]
Triaged as SITES-503

**Comment by ltankey** [comment]
Delivered in v0.9.0
