### ISSUE TITLE
Apply Highlighted Words style for Department listing page

### ISSUE THREAD

**Issue by hannah-ustwo** [AusDTO/gov-au-beta#311]
[Department listing](https://gov-au-beta.apps.platform.digital.gov.au/departments) currently looks like this...
![image](https://cloud.githubusercontent.com/assets/19661064/17239314/784a6a62-55a6-11e6-95a1-e8846120b864.png)

Should be following [Highlighted Words style](http://gov-au-ui-kit.apps.staging.digital.gov.au/section-list-styles.html#guide-list-styles-4-highlighted-word-style)

![image](https://cloud.githubusercontent.com/assets/19661064/17239367/e8c1cf24-55a6-11e6-90bf-241647eb9c61.png)

**Comment by hannah-ustwo** [comment]
Note: it was decided with @alex-dto and @klepas that this will be held off on until after 4 Aug

**Comment by catherineedwards** [comment]
See `SITES-433`

**Comment by ltankey** [comment]
Delivered in v0.9.0
