### ISSUE TITLE
Can't open NSW, TAS and Vic Public holidays

### ISSUE THREAD

**Issue by nicholasgkdto** [AusDTO/gov-au-beta#339]
I should be able to open the following links

platform/times-and-dates/australian-public-holidays/new-south-wales
platform/times-and-dates/australian-public-holidays/victoria
platform/times-and-dates/australian-public-holidays/australian-capital-territory

platform/times-and-dates/australian-daylight-saving/new-south-wales
platform/times-and-dates/australian-daylight-saving/victoria
platform/times-and-dates/australian-daylight-saving/australian-capital-territory

platform/times-and-dates/school-holidays-and-term-dates/new-south-wales
platform/times-and-dates/school-holidays-and-term-dates/australian-capital-territory

**Comment by ltankey** [comment]
Delivered in v0.9.0
