### ISSUE TITLE
Department listing style

### ISSUE THREAD

**Issue by AlzbetaT** [AusDTO/gov-au-beta#340]
@catherineedwards 

Please update the listing style for this page: 
/departments
using ul.list.highlighted as per:
/ministers

Please also include a one line summary below the Department name as per the prototype:
/all-agencies.html

**Comment by ltankey** [comment]
@AlzbetaT is the one line summary expected to be within the hero or outside of it?

**Comment by catherineedwards** [comment]
Tracking as `SITES-530`

**Comment by AlzbetaT** [comment]
@ltankey

**Comment by AlzbetaT** [comment]
@ltankey visual reference from the agency prototype/all-agencies.html
![screen shot 2016-08-02 at 9 53 23 am](https://cloud.githubusercontent.com/assets/19522643/17312589/0dada982-5897-11e6-90a5-18667801e33c.png)

**Comment by ltankey** [comment]
@AlzbetaT is that text coming from the short_summary field?

**Comment by AlzbetaT** [comment]
@ltankey the text has been adapted from the short_summary field. It's not identical.

Can you use the one line summaries from that page in the prototype for now. It is something we will have to systemise later.

http://govau-agency.apps.staging.digital.gov.au/all-agencies.html

**Comment by ltankey** [comment]
No - the fields are coming from models, not from static HTML which we can fudge. 

Could you please update the short-summaries of the Department home pages to have the desired text? They should match any list items as per @maadonna's IA.

**Comment by AlzbetaT** [comment]
@ltankey let's pause this issue until post demo. Have spoken to Michael in content about this, he is unable to action now. Thanks!

**Comment by ltankey** [comment]
@AlzbetaT the changes for this have already been merged and will be released this afternoon. Are there any further actions we need to take for demo?

**Comment by AlzbetaT** [comment]
@ltankey no, if we were able to update the listing styles (sans summaries) that's great!

**Comment by ltankey** [comment]
Ok no worries @AlzbetaT - the summaries can either be removed via content or we can create a change to stop them displaying on the `/departments` page - I presume you want the latter?

**Comment by AlzbetaT** [comment]
@ltankey Great yes, for now the latter (not appearing on the Department listing page).

**Comment by tessereth** [comment]
Fixed in 1.0.0
