### ISSUE TITLE
Alignment of items inside 'Information and services' on landing pages

### ISSUE THREAD

**Issue by michaelhugill** [AusDTO/gov-au-beta#341]
As flagged with @micapam (and possibly a UI-Kit issue):

The alignment of the three items within the 'Information and services' module on the landing pages of sections appears to be out of kilter in some cases. Here's an example:

![screen shot 2016-08-02 at 9 26 10 am](https://cloud.githubusercontent.com/assets/17994414/17312196/5a68d8d0-5894-11e6-887b-7ae792009eca.png)  

See excessive space between left and middle items and not enough space between middle and right items – possible due to text wrapping.

**Comment by tessereth** [comment]
Can you tell me which page this is on?

**Comment by tessereth** [comment]
Never mind. I found it at `/department-of-finance`.

**Comment by catherineedwards** [comment]
Tracking as `SITES-531`

**Comment by klepas** [comment]
Still mind-blown why these are `<table>` to begin with… -_-

**Comment by TrebBrennan** [comment]
Confirmed with @AlzbetaT that we can live with this for now until a more robust solution for this thing can get worked on
