### ISSUE TITLE
Homepage category listings

### ISSUE THREAD

**Issue by AlzbetaT** [AusDTO/gov-au-beta#342]
@catherineedwards 

Please adjust length of side-border in the Category listing styles on home page:

Screenshot showing: current (left) and desired (right)
![screen shot 2016-08-02 at 9 38 56 am](https://cloud.githubusercontent.com/assets/19522643/17312727/33c6790e-5898-11e6-8d9e-62dcbf31c6fc.png)

**Comment by catherineedwards** [comment]
Tracking as `SITES-532`

**Comment by AlzbetaT** [comment]
@catherineedwards 

See pixel height of element in screenshot:
![screen shot 2016-08-02 at 10 05 32 am](https://cloud.githubusercontent.com/assets/19522643/17312803/d7820950-5898-11e6-8a06-06a8893c1199.png)

**Comment by catherineedwards** [comment]
Beautiful, thank you @AlzbetaT

**Comment by tessereth** [comment]
Fixed in 1.0.0

**Comment by klepas** [comment]
Hey @AlzbetaT,

Was this hotfixed in Sites — this is a list style in uikit; if the change should be permanent it should be reflected in our repo.
