### ISSUE TITLE
Abstract style missing

### ISSUE THREAD

**Issue by AlzbetaT** [AusDTO/gov-au-beta#344]
@catherineedwards 

Abstract styling is missing from first paragraph on all Departmental landing pages:
platform.digital.gov.au/department-of-communications-and-the-arts

Screenshot showing current (left) and desired (right)
![screen shot 2016-08-02 at 10 23 31 am](https://cloud.githubusercontent.com/assets/19522643/17313011/62196886-589b-11e6-9464-aaace5553688.png)

Abstract style also seems to be missing across the board on Topic pages:
platform.digital.gov.au/television-tv-reception/setting-up-digital-tv
platform.digital.gov.au/television-tv-reception

Abstract style also missing on Minister's landing pages:
platform.digital.gov.au/minister-for-communications

**Comment by catherineedwards** [comment]
Tracking as `SITES-537`

**Comment by AlzbetaT** [comment]
@catherineedwards 

Abstract style also seems to be missing across the board on Topic pages:
platform.digital.gov.au/television-tv-reception/setting-up-digital-tv
platform.digital.gov.au/television-tv-reception

**Comment by tessereth** [comment]
Fixed in 1.0.0
