### ISSUE TITLE
Summary on Minister Page not matching prototype styling

### ISSUE THREAD

**Issue by Alex-DTO** [AusDTO/gov-au-beta#345]
LOW PRIORITY 

Prototype:
/comms-minister/index.html
Text at the top is larger than the standard body text size, and has a horizontal rule spaced as per design

Platform
/prime-minister

Copy is body text size and has no space between it and the horizontal rule

**Comment by catherineedwards** [comment]
Tracking as `SITES-538`

**Comment by tessereth** [comment]
Should be fixed by #350
