### ISSUE TITLE
Change image of Minister on Departmental landing pages

### ISSUE THREAD

**Issue by AlzbetaT** [AusDTO/gov-au-beta#347]
@catherineedwards 

On the Departmental landing pages, use the image of the Minister from the Minister's homepage in the same proportion.

Screenshot showing current (left) and desired (right)
![screen shot 2016-08-02 at 10 40 09 am](https://cloud.githubusercontent.com/assets/19522643/17313281/92de14ec-589d-11e6-9cfb-422b9c2a47a0.png)

**Comment by catherineedwards** [comment]
From @AlzbetaT : All the correct images are on the Ministers Landing pages are in platform, they just need to be pulled into the Departmental Minister’s module in the same proportion without being cropped

**Comment by catherineedwards** [comment]
Tracking on `SITES-539`

**Comment by AlzbetaT** [comment]
@catherineedwards look ace@ Thanks everyone!
