### ISSUE TITLE
Large text links should follow colors of standard link states

### ISSUE THREAD

**Issue by hannah-ustwo** [AusDTO/gov-au-beta#349]
Should follow the default link styling (colors) for dark text on light BG (black with blue underline, then blue highlight on hover)

Expected to look like this
![link-states_a](https://cloud.githubusercontent.com/assets/19661064/17313582/484b8740-58a0-11e6-867e-020104dbfdf5.gif)

But looks like this
![210c72ef7d3c6f1268c946cb67074289](https://cloud.githubusercontent.com/assets/19661064/17313542/dd0d4360-589f-11e6-8f93-0578c14a7597.gif)

**Comment by simonschwartz** [comment]
Thanks @hannah-ustwo I believe the design @AlzbetaT supplied had these items as Aqua on white. Is it possible the both of you could have a quick chat about the best way forward? Then I'm more than happy to update :)

**Comment by AlzbetaT** [comment]
@hannah-ustwo @simonschwartz the colour on the large typographic elements references the use of blue in the "About Australia" modules. I would leave it as is for now. The content and styling of the "About Australia" modules will be iterated on later anyway.

**Comment by catherineedwards** [comment]
Tracking as `SITES-540`

**Comment by ltankey** [comment]
Happy to revisit when there's design consensus.
