### ISSUE TITLE
MINOR - Change 'Next Public Holiday' copy on Global Home widget

### ISSUE THREAD

**Issue by Alex-DTO** [AusDTO/gov-au-beta#369]
The vision for this widget is for it to geolocate the user and show the relevant public holiday to them, however that is not yet achievable. As a result, please update the current copy of 'Next public holiday' to 'Next national public holiday'

![image](https://cloud.githubusercontent.com/assets/20697521/17354852/7c424030-598f-11e6-8e40-cec89997116d.png)

**Comment by catherineedwards** [comment]
Tracking as `SITES-580`

**Comment by maxious** [comment]
Fixed in next release.

**Comment by maxious** [comment]
Deployed.

![](https://cloud.githubusercontent.com/assets/81432/17683918/6fba93e8-639a-11e6-867b-445fd87a9b59.png)
