### ISSUE TITLE
Remove text from short summary sections from two pages

### ISSUE THREAD

**Issue by catherineedwards** [AusDTO/gov-au-beta#372]
Issue #338 inadvertently reintroduced text that had been removed from the short summary sections in a previous build of the platform.

Please remove the text, "The Australian Government's ministers include Cabinet ministers, outer ministers, assistant ministers, ministers assisting and parliamentary secretaries," from `/ministers`

Please remove the text, "The Australian Government has 18 departments and 189 agencies," from `/departments`

However, please retain the functionality of the short summaries for now. Please just remove the text.

**Comment by ltankey** [comment]
Doesn't #338 explicitly ask for the content to be added?

**Comment by streetdaddy** [comment]
Tracked in SITES-607

**Comment by streetdaddy** [comment]
Released to Production in https://github.com/AusDTO/gov-au-beta/releases/tag/v1.1.0
