### ISSUE TITLE
Markdown underscores

### ISSUE THREAD

**Issue by michaelhugill** [AusDTO/gov-au-beta#386]
@ltankey @klepas I'm thinking one of you two might be able to help with this.

When we upload a twitter handle with underscores in it, instead of displaying as @business_gov_au, it displays as @businessgovau (with 'gov' italicised).

Here's the page: https://gov-au-beta.apps.platform.digital.gov.au/department-of-industry-innovation-and-science/contact-us

Thanks.

**Comment by catherineedwards** [comment]
Querying further with UI Kit and Platform teams before adding to backlog.

**Comment by streetdaddy** [comment]
@michaelhugill you need to 'escape' markdown syntax with a backslash.  So the correct markdown to insert that twitter handle would be:

`@business\_gov\_au`

Please confirm that works so we can close this issue.

**Comment by ltankey** [comment]
Thanks @michaelhugill - this is indeed a conflict between markdown syntax and the word you're trying to create.

Could you try escaping the underscores in the content, and confirm that it renders correctly?

This should be achievable with:

`@business\_gov\_au`

**Comment by klepas** [comment]
^

**Comment by catherineedwards** [comment]
Provided that @streetdaddy's instruction does provide the fix, is there markdown documentation/instruction to which we can add to inform all users?

**Comment by catherineedwards** [comment]
@michaelhugill Please let us know whether @streetdaddy's resolves your issue by replying to this thread.

**Comment by klepas** [comment]
@catherineedwards I had a quick look online. There are a number of places, but nothing super succinct where digging or familiarity with say stackexchange wasn’t a big help…

For reference, since Markdown uses certain characters for its syntax, you can use the backslash (`\`) to escape the following:

```
`   backtick
*   asterisk
_   underscore
{}  curly braces
[]  square brackets
()  parentheses
#   hash mark
+   plus sign
-   minus sign (hyphen)
.   dot
!   exclamation mark
```

**Comment by michaelhugill** [comment]
Problem fixed. Thanks, everyone. I'll also share this with other content designers.
