### ISSUE TITLE
Ability for author to create 'greyed out' hyperlinks with markdown

### ISSUE THREAD

**Issue by Alex-DTO** [AusDTO/gov-au-beta#415]
As a content author
I want to be able to easily represent a dead/not yet valid hyperlink in body text to a reader
So that the reader is able to understand that there will be a link placed here at a later date

Content body text (along with other areas of the site) needs to be able to represent dead links to a user in order to show that there are to be links here at some point - this helps to expand the visibility of the content model, whereby a dead link infers that there has already been thinking about a page to sit behind that link.

Guides team have already released ability to create the dead link visuals using html in the markdown editor
http://gov-au-ui-kit.apps.staging.digital.gov.au/section-link-styles.html#guide-link-styles-3-placeholder-links

Requirement is to create markdown that will allow a content author to create this functionality without having to paste HTML code into the page for each link.

**Comment by Alex-DTO** [comment]
Point for Discussion...

Currently in the editor we have used the following to denote a dead link:

[some text](#)

Suggestion is that ](#) is recognised to specify a dead link... This doesn't appear anywhere else in the content and would also save a lot of content debt in changing it to a different markdown instruction!

**Comment by streetdaddy** [comment]
Triaged as SITES-627

**Comment by bjgordon** [comment]
This was released in v.1.2.0
