### ISSUE TITLE
Ability for an admin to edit footer links

### ISSUE THREAD

**Issue by Alex-DTO** [AusDTO/gov-au-beta#422]
4 or 5 (TBC) footer links to be created
Globally visible across the gov.au website
Hyperlink to a single page of content
Admin must be able to change the name of the footer link and page
Replicate current styles used across gov.au

Markdown use desirable for the content creation, but not essential so long as current styles can be replicated by the admin author

**Comment by streetdaddy** [comment]
triaged as SITES-628

**Comment by maxious** [comment]
Managing the "About GOV.AU" section manages the footer pages and links including link ordering.
