### ISSUE TITLE
Single quotes in markdown links render as #39;

### ISSUE THREAD

**Issue by nicholasgkdto** [AusDTO/gov-au-beta#462]
When you add a ' in to the text for a link it shows up as `#39;`

ie 
`the cat's foot and [the dog's leg](http://www.example.com)`

show up as 

the cat's foot and [the dog#39;s leg](http://www.example.com)

only happens in links

see example 
platform/attorney-general-s-department/contact-us#social-media

**Comment by ltankey** [comment]
Confirmed, -> SITES-674.

**Comment by bjgordon** [comment]
Fixed in v1.3.0
