### ISSUE TITLE
Alignment of shaded list borders in Dates & Times

### ISSUE THREAD

**Issue by Alex-DTO** [AusDTO/gov-au-beta#463]
The alternating colours are no longer aligned when applied to the Dates & Times pages

![image](https://cloud.githubusercontent.com/assets/20697521/18154280/aa8f09e6-7046-11e6-99d0-92e2ddc60b89.png)

**Comment by ltankey** [comment]
This looks like it's the result of _phone-numers.scss supplying a box-shadow for `.highlighted`.

@simonschwartz may be able to comment further.

**Comment by bjgordon** [comment]
Fixed in v1.3.0
