### ISSUE TITLE
Update to our ministers module on department landing pages

### ISSUE THREAD

**Issue by michaelhugill** [AusDTO/gov-au-beta#487]
Expected outcome
- When only one minister is tagged in the 'Our ministers' module of a department landing page, the module title needs to change to 'Our Minister'. 

Actual outcome
- Current example of one minister sitting under a pluralised module title: https://gov-au-beta.apps.platform.digital.gov.au/department-of-agriculture-and-water-resources 

@streetdaddy Could you please add anything I've missed?

**Comment by maxious** [comment]
Sounds like a job for http://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html#method-i-pluralize
